### ISSUE TITLE
CORS error when running locally

### ISSUE THREAD

**Issue by spankyed** [thakkaryash94/chroma-ui#4]
![image](https://github.com/thakkaryash94/chroma-ui/assets/23444930/62d39040-d123-47f2-bee6-2e3032df48d3)

Unfamiliar with nextjs so cant easily fix it.

**Comment by thakkaryash94** [comment]
The frontend is running on 3000 whereas the chroma db is running on 8000. So it's the chroma db server throwing the error. There are two ways to solve this.

1. If you are using docker image, you can pass `CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]` as an environment variable to allow other host:port applications to send the request.
```yaml
version: '3.9'

networks:
  net:
    driver: bridge
services:
  server:
    container_name: chroma
    image: ghcr.io/chroma-core/chroma:0.4.18
    ports:
      - 8000:8000
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
```

2. If you are running chroma db inside python application, eg using fastapi, you need to enable cors and pass `allow_origins` in middleware. https://fastapi.tiangolo.com/tutorial/cors/
